// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var ppx = ppx || {};

/**
 * @enum
 */
ppx.MessageBody = {
  NONE: 0, 0: 'NONE',
  Handshake: 1, 1: 'Handshake',
  HandshakeResult: 2, 2: 'HandshakeResult',
  Run: 3, 3: 'Run',
  RunResult: 4, 4: 'RunResult',
  Sample: 5, 5: 'Sample',
  SampleResult: 6, 6: 'SampleResult',
  Observe: 7, 7: 'Observe',
  ObserveResult: 8, 8: 'ObserveResult',
  Tag: 9, 9: 'Tag',
  TagResult: 10, 10: 'TagResult',
  Reset: 11, 11: 'Reset'
};

/**
 * @enum
 */
ppx.Distribution = {
  NONE: 0, 0: 'NONE',
  Normal: 1, 1: 'Normal',
  Uniform: 2, 2: 'Uniform',
  Categorical: 3, 3: 'Categorical',
  Poisson: 4, 4: 'Poisson',
  Beta: 5, 5: 'Beta',
  Gamma: 6, 6: 'Gamma',
  LogNormal: 7, 7: 'LogNormal',
  Exponential: 8, 8: 'Exponential',
  Weibull: 9, 9: 'Weibull'
};

/**
 * @constructor
 */
ppx.Message = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Message}
 */
ppx.Message.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Message=} obj
 * @returns {ppx.Message}
 */
ppx.Message.getRootAsMessage = function(bb, obj) {
  return (obj || new ppx.Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
ppx.Message.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PPXF');
};

/**
 * @returns {ppx.MessageBody}
 */
ppx.Message.prototype.bodyType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {ppx.MessageBody} */ (this.bb.readUint8(this.bb_pos + offset)) : ppx.MessageBody.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
ppx.Message.prototype.body = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Message.startMessage = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ppx.MessageBody} bodyType
 */
ppx.Message.addBodyType = function(builder, bodyType) {
  builder.addFieldInt8(0, bodyType, ppx.MessageBody.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bodyOffset
 */
ppx.Message.addBody = function(builder, bodyOffset) {
  builder.addFieldOffset(1, bodyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Message.endMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
ppx.Message.finishMessageBuffer = function(builder, offset) {
  builder.finish(offset, 'PPXF');
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ppx.MessageBody} bodyType
 * @param {flatbuffers.Offset} bodyOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Message.createMessage = function(builder, bodyType, bodyOffset) {
  ppx.Message.startMessage(builder);
  ppx.Message.addBodyType(builder, bodyType);
  ppx.Message.addBody(builder, bodyOffset);
  return ppx.Message.endMessage(builder);
}

/**
 * @constructor
 */
ppx.Tensor = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Tensor}
 */
ppx.Tensor.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor}
 */
ppx.Tensor.getRootAsTensor = function(bb, obj) {
  return (obj || new ppx.Tensor).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @returns {number}
 */
ppx.Tensor.prototype.data = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat64(this.bb.__vector(this.bb_pos + offset) + index * 8) : 0;
};

/**
 * @returns {number}
 */
ppx.Tensor.prototype.dataLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Float64Array}
 */
ppx.Tensor.prototype.dataArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? new Float64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
ppx.Tensor.prototype.shape = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
ppx.Tensor.prototype.shapeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
ppx.Tensor.prototype.shapeArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Tensor.startTensor = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
ppx.Tensor.addData = function(builder, dataOffset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
ppx.Tensor.createDataVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addFloat64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ppx.Tensor.startDataVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shapeOffset
 */
ppx.Tensor.addShape = function(builder, shapeOffset) {
  builder.addFieldOffset(1, shapeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
ppx.Tensor.createShapeVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ppx.Tensor.startShapeVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Tensor.endTensor = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 * @param {flatbuffers.Offset} shapeOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Tensor.createTensor = function(builder, dataOffset, shapeOffset) {
  ppx.Tensor.startTensor(builder);
  ppx.Tensor.addData(builder, dataOffset);
  ppx.Tensor.addShape(builder, shapeOffset);
  return ppx.Tensor.endTensor(builder);
}

/**
 * @constructor
 */
ppx.Handshake = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Handshake}
 */
ppx.Handshake.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Handshake=} obj
 * @returns {ppx.Handshake}
 */
ppx.Handshake.getRootAsHandshake = function(bb, obj) {
  return (obj || new ppx.Handshake).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Handshake.prototype.systemName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Handshake.startHandshake = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} systemNameOffset
 */
ppx.Handshake.addSystemName = function(builder, systemNameOffset) {
  builder.addFieldOffset(0, systemNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Handshake.endHandshake = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} systemNameOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Handshake.createHandshake = function(builder, systemNameOffset) {
  ppx.Handshake.startHandshake(builder);
  ppx.Handshake.addSystemName(builder, systemNameOffset);
  return ppx.Handshake.endHandshake(builder);
}

/**
 * @constructor
 */
ppx.HandshakeResult = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.HandshakeResult}
 */
ppx.HandshakeResult.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.HandshakeResult=} obj
 * @returns {ppx.HandshakeResult}
 */
ppx.HandshakeResult.getRootAsHandshakeResult = function(bb, obj) {
  return (obj || new ppx.HandshakeResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.HandshakeResult.prototype.systemName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.HandshakeResult.prototype.modelName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.HandshakeResult.startHandshakeResult = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} systemNameOffset
 */
ppx.HandshakeResult.addSystemName = function(builder, systemNameOffset) {
  builder.addFieldOffset(0, systemNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} modelNameOffset
 */
ppx.HandshakeResult.addModelName = function(builder, modelNameOffset) {
  builder.addFieldOffset(1, modelNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.HandshakeResult.endHandshakeResult = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} systemNameOffset
 * @param {flatbuffers.Offset} modelNameOffset
 * @returns {flatbuffers.Offset}
 */
ppx.HandshakeResult.createHandshakeResult = function(builder, systemNameOffset, modelNameOffset) {
  ppx.HandshakeResult.startHandshakeResult(builder);
  ppx.HandshakeResult.addSystemName(builder, systemNameOffset);
  ppx.HandshakeResult.addModelName(builder, modelNameOffset);
  return ppx.HandshakeResult.endHandshakeResult(builder);
}

/**
 * @constructor
 */
ppx.Run = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Run}
 */
ppx.Run.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Run=} obj
 * @returns {ppx.Run}
 */
ppx.Run.getRootAsRun = function(bb, obj) {
  return (obj || new ppx.Run).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Run.startRun = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Run.endRun = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Run.createRun = function(builder) {
  ppx.Run.startRun(builder);
  return ppx.Run.endRun(builder);
}

/**
 * @constructor
 */
ppx.RunResult = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.RunResult}
 */
ppx.RunResult.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.RunResult=} obj
 * @returns {ppx.RunResult}
 */
ppx.RunResult.getRootAsRunResult = function(bb, obj) {
  return (obj || new ppx.RunResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.RunResult.prototype.result = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.RunResult.startRunResult = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} resultOffset
 */
ppx.RunResult.addResult = function(builder, resultOffset) {
  builder.addFieldOffset(0, resultOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.RunResult.endRunResult = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} resultOffset
 * @returns {flatbuffers.Offset}
 */
ppx.RunResult.createRunResult = function(builder, resultOffset) {
  ppx.RunResult.startRunResult(builder);
  ppx.RunResult.addResult(builder, resultOffset);
  return ppx.RunResult.endRunResult(builder);
}

/**
 * @constructor
 */
ppx.Sample = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Sample}
 */
ppx.Sample.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Sample=} obj
 * @returns {ppx.Sample}
 */
ppx.Sample.getRootAsSample = function(bb, obj) {
  return (obj || new ppx.Sample).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Sample.prototype.address = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Sample.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {ppx.Distribution}
 */
ppx.Sample.prototype.distributionType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {ppx.Distribution} */ (this.bb.readUint8(this.bb_pos + offset)) : ppx.Distribution.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
ppx.Sample.prototype.distribution = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @returns {boolean}
 */
ppx.Sample.prototype.control = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @returns {boolean}
 */
ppx.Sample.prototype.replace = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Sample.startSample = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 */
ppx.Sample.addAddress = function(builder, addressOffset) {
  builder.addFieldOffset(0, addressOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
ppx.Sample.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ppx.Distribution} distributionType
 */
ppx.Sample.addDistributionType = function(builder, distributionType) {
  builder.addFieldInt8(2, distributionType, ppx.Distribution.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} distributionOffset
 */
ppx.Sample.addDistribution = function(builder, distributionOffset) {
  builder.addFieldOffset(3, distributionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} control
 */
ppx.Sample.addControl = function(builder, control) {
  builder.addFieldInt8(4, +control, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} replace
 */
ppx.Sample.addReplace = function(builder, replace) {
  builder.addFieldInt8(5, +replace, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Sample.endSample = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 * @param {flatbuffers.Offset} nameOffset
 * @param {ppx.Distribution} distributionType
 * @param {flatbuffers.Offset} distributionOffset
 * @param {boolean} control
 * @param {boolean} replace
 * @returns {flatbuffers.Offset}
 */
ppx.Sample.createSample = function(builder, addressOffset, nameOffset, distributionType, distributionOffset, control, replace) {
  ppx.Sample.startSample(builder);
  ppx.Sample.addAddress(builder, addressOffset);
  ppx.Sample.addName(builder, nameOffset);
  ppx.Sample.addDistributionType(builder, distributionType);
  ppx.Sample.addDistribution(builder, distributionOffset);
  ppx.Sample.addControl(builder, control);
  ppx.Sample.addReplace(builder, replace);
  return ppx.Sample.endSample(builder);
}

/**
 * @constructor
 */
ppx.SampleResult = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.SampleResult}
 */
ppx.SampleResult.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.SampleResult=} obj
 * @returns {ppx.SampleResult}
 */
ppx.SampleResult.getRootAsSampleResult = function(bb, obj) {
  return (obj || new ppx.SampleResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.SampleResult.prototype.result = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.SampleResult.startSampleResult = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} resultOffset
 */
ppx.SampleResult.addResult = function(builder, resultOffset) {
  builder.addFieldOffset(0, resultOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.SampleResult.endSampleResult = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} resultOffset
 * @returns {flatbuffers.Offset}
 */
ppx.SampleResult.createSampleResult = function(builder, resultOffset) {
  ppx.SampleResult.startSampleResult(builder);
  ppx.SampleResult.addResult(builder, resultOffset);
  return ppx.SampleResult.endSampleResult(builder);
}

/**
 * @constructor
 */
ppx.Observe = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Observe}
 */
ppx.Observe.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Observe=} obj
 * @returns {ppx.Observe}
 */
ppx.Observe.getRootAsObserve = function(bb, obj) {
  return (obj || new ppx.Observe).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Observe.prototype.address = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Observe.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {ppx.Distribution}
 */
ppx.Observe.prototype.distributionType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {ppx.Distribution} */ (this.bb.readUint8(this.bb_pos + offset)) : ppx.Distribution.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
ppx.Observe.prototype.distribution = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Observe.prototype.value = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Observe.startObserve = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 */
ppx.Observe.addAddress = function(builder, addressOffset) {
  builder.addFieldOffset(0, addressOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
ppx.Observe.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {ppx.Distribution} distributionType
 */
ppx.Observe.addDistributionType = function(builder, distributionType) {
  builder.addFieldInt8(2, distributionType, ppx.Distribution.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} distributionOffset
 */
ppx.Observe.addDistribution = function(builder, distributionOffset) {
  builder.addFieldOffset(3, distributionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
ppx.Observe.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(4, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Observe.endObserve = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 * @param {flatbuffers.Offset} nameOffset
 * @param {ppx.Distribution} distributionType
 * @param {flatbuffers.Offset} distributionOffset
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Observe.createObserve = function(builder, addressOffset, nameOffset, distributionType, distributionOffset, valueOffset) {
  ppx.Observe.startObserve(builder);
  ppx.Observe.addAddress(builder, addressOffset);
  ppx.Observe.addName(builder, nameOffset);
  ppx.Observe.addDistributionType(builder, distributionType);
  ppx.Observe.addDistribution(builder, distributionOffset);
  ppx.Observe.addValue(builder, valueOffset);
  return ppx.Observe.endObserve(builder);
}

/**
 * @constructor
 */
ppx.ObserveResult = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.ObserveResult}
 */
ppx.ObserveResult.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.ObserveResult=} obj
 * @returns {ppx.ObserveResult}
 */
ppx.ObserveResult.getRootAsObserveResult = function(bb, obj) {
  return (obj || new ppx.ObserveResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.ObserveResult.startObserveResult = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.ObserveResult.endObserveResult = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.ObserveResult.createObserveResult = function(builder) {
  ppx.ObserveResult.startObserveResult(builder);
  return ppx.ObserveResult.endObserveResult(builder);
}

/**
 * @constructor
 */
ppx.Tag = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Tag}
 */
ppx.Tag.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Tag=} obj
 * @returns {ppx.Tag}
 */
ppx.Tag.getRootAsTag = function(bb, obj) {
  return (obj || new ppx.Tag).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Tag.prototype.address = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ppx.Tag.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Tag.prototype.value = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Tag.startTag = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 */
ppx.Tag.addAddress = function(builder, addressOffset) {
  builder.addFieldOffset(0, addressOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
ppx.Tag.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
ppx.Tag.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(2, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Tag.endTag = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 * @param {flatbuffers.Offset} nameOffset
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Tag.createTag = function(builder, addressOffset, nameOffset, valueOffset) {
  ppx.Tag.startTag(builder);
  ppx.Tag.addAddress(builder, addressOffset);
  ppx.Tag.addName(builder, nameOffset);
  ppx.Tag.addValue(builder, valueOffset);
  return ppx.Tag.endTag(builder);
}

/**
 * @constructor
 */
ppx.TagResult = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.TagResult}
 */
ppx.TagResult.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.TagResult=} obj
 * @returns {ppx.TagResult}
 */
ppx.TagResult.getRootAsTagResult = function(bb, obj) {
  return (obj || new ppx.TagResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.TagResult.startTagResult = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.TagResult.endTagResult = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.TagResult.createTagResult = function(builder) {
  ppx.TagResult.startTagResult(builder);
  return ppx.TagResult.endTagResult(builder);
}

/**
 * @constructor
 */
ppx.Reset = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Reset}
 */
ppx.Reset.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Reset=} obj
 * @returns {ppx.Reset}
 */
ppx.Reset.getRootAsReset = function(bb, obj) {
  return (obj || new ppx.Reset).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Reset.startReset = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Reset.endReset = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Reset.createReset = function(builder) {
  ppx.Reset.startReset(builder);
  return ppx.Reset.endReset(builder);
}

/**
 * @constructor
 */
ppx.Normal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Normal}
 */
ppx.Normal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Normal=} obj
 * @returns {ppx.Normal}
 */
ppx.Normal.getRootAsNormal = function(bb, obj) {
  return (obj || new ppx.Normal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Normal.prototype.mean = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Normal.prototype.stddev = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Normal.startNormal = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} meanOffset
 */
ppx.Normal.addMean = function(builder, meanOffset) {
  builder.addFieldOffset(0, meanOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} stddevOffset
 */
ppx.Normal.addStddev = function(builder, stddevOffset) {
  builder.addFieldOffset(1, stddevOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Normal.endNormal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} meanOffset
 * @param {flatbuffers.Offset} stddevOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Normal.createNormal = function(builder, meanOffset, stddevOffset) {
  ppx.Normal.startNormal(builder);
  ppx.Normal.addMean(builder, meanOffset);
  ppx.Normal.addStddev(builder, stddevOffset);
  return ppx.Normal.endNormal(builder);
}

/**
 * @constructor
 */
ppx.Uniform = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Uniform}
 */
ppx.Uniform.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Uniform=} obj
 * @returns {ppx.Uniform}
 */
ppx.Uniform.getRootAsUniform = function(bb, obj) {
  return (obj || new ppx.Uniform).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Uniform.prototype.low = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Uniform.prototype.high = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Uniform.startUniform = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} lowOffset
 */
ppx.Uniform.addLow = function(builder, lowOffset) {
  builder.addFieldOffset(0, lowOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} highOffset
 */
ppx.Uniform.addHigh = function(builder, highOffset) {
  builder.addFieldOffset(1, highOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Uniform.endUniform = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} lowOffset
 * @param {flatbuffers.Offset} highOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Uniform.createUniform = function(builder, lowOffset, highOffset) {
  ppx.Uniform.startUniform(builder);
  ppx.Uniform.addLow(builder, lowOffset);
  ppx.Uniform.addHigh(builder, highOffset);
  return ppx.Uniform.endUniform(builder);
}

/**
 * @constructor
 */
ppx.Categorical = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Categorical}
 */
ppx.Categorical.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Categorical=} obj
 * @returns {ppx.Categorical}
 */
ppx.Categorical.getRootAsCategorical = function(bb, obj) {
  return (obj || new ppx.Categorical).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Categorical.prototype.probs = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Categorical.startCategorical = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} probsOffset
 */
ppx.Categorical.addProbs = function(builder, probsOffset) {
  builder.addFieldOffset(0, probsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Categorical.endCategorical = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} probsOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Categorical.createCategorical = function(builder, probsOffset) {
  ppx.Categorical.startCategorical(builder);
  ppx.Categorical.addProbs(builder, probsOffset);
  return ppx.Categorical.endCategorical(builder);
}

/**
 * @constructor
 */
ppx.Poisson = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Poisson}
 */
ppx.Poisson.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Poisson=} obj
 * @returns {ppx.Poisson}
 */
ppx.Poisson.getRootAsPoisson = function(bb, obj) {
  return (obj || new ppx.Poisson).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Poisson.prototype.rate = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Poisson.startPoisson = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rateOffset
 */
ppx.Poisson.addRate = function(builder, rateOffset) {
  builder.addFieldOffset(0, rateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Poisson.endPoisson = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rateOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Poisson.createPoisson = function(builder, rateOffset) {
  ppx.Poisson.startPoisson(builder);
  ppx.Poisson.addRate(builder, rateOffset);
  return ppx.Poisson.endPoisson(builder);
}

/**
 * @constructor
 */
ppx.Beta = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Beta}
 */
ppx.Beta.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Beta=} obj
 * @returns {ppx.Beta}
 */
ppx.Beta.getRootAsBeta = function(bb, obj) {
  return (obj || new ppx.Beta).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Beta.prototype.concentration0 = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Beta.prototype.concentration1 = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Beta.startBeta = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concentration0Offset
 */
ppx.Beta.addConcentration0 = function(builder, concentration0Offset) {
  builder.addFieldOffset(0, concentration0Offset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concentration1Offset
 */
ppx.Beta.addConcentration1 = function(builder, concentration1Offset) {
  builder.addFieldOffset(1, concentration1Offset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Beta.endBeta = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concentration0Offset
 * @param {flatbuffers.Offset} concentration1Offset
 * @returns {flatbuffers.Offset}
 */
ppx.Beta.createBeta = function(builder, concentration0Offset, concentration1Offset) {
  ppx.Beta.startBeta(builder);
  ppx.Beta.addConcentration0(builder, concentration0Offset);
  ppx.Beta.addConcentration1(builder, concentration1Offset);
  return ppx.Beta.endBeta(builder);
}

/**
 * @constructor
 */
ppx.Gamma = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Gamma}
 */
ppx.Gamma.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Gamma=} obj
 * @returns {ppx.Gamma}
 */
ppx.Gamma.getRootAsGamma = function(bb, obj) {
  return (obj || new ppx.Gamma).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Gamma.prototype.concentration = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Gamma.prototype.rate = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Gamma.startGamma = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concentrationOffset
 */
ppx.Gamma.addConcentration = function(builder, concentrationOffset) {
  builder.addFieldOffset(0, concentrationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rateOffset
 */
ppx.Gamma.addRate = function(builder, rateOffset) {
  builder.addFieldOffset(1, rateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Gamma.endGamma = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concentrationOffset
 * @param {flatbuffers.Offset} rateOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Gamma.createGamma = function(builder, concentrationOffset, rateOffset) {
  ppx.Gamma.startGamma(builder);
  ppx.Gamma.addConcentration(builder, concentrationOffset);
  ppx.Gamma.addRate(builder, rateOffset);
  return ppx.Gamma.endGamma(builder);
}

/**
 * @constructor
 */
ppx.LogNormal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.LogNormal}
 */
ppx.LogNormal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.LogNormal=} obj
 * @returns {ppx.LogNormal}
 */
ppx.LogNormal.getRootAsLogNormal = function(bb, obj) {
  return (obj || new ppx.LogNormal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.LogNormal.prototype.mean = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.LogNormal.prototype.stddev = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.LogNormal.startLogNormal = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} meanOffset
 */
ppx.LogNormal.addMean = function(builder, meanOffset) {
  builder.addFieldOffset(0, meanOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} stddevOffset
 */
ppx.LogNormal.addStddev = function(builder, stddevOffset) {
  builder.addFieldOffset(1, stddevOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.LogNormal.endLogNormal = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} meanOffset
 * @param {flatbuffers.Offset} stddevOffset
 * @returns {flatbuffers.Offset}
 */
ppx.LogNormal.createLogNormal = function(builder, meanOffset, stddevOffset) {
  ppx.LogNormal.startLogNormal(builder);
  ppx.LogNormal.addMean(builder, meanOffset);
  ppx.LogNormal.addStddev(builder, stddevOffset);
  return ppx.LogNormal.endLogNormal(builder);
}

/**
 * @constructor
 */
ppx.Exponential = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Exponential}
 */
ppx.Exponential.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Exponential=} obj
 * @returns {ppx.Exponential}
 */
ppx.Exponential.getRootAsExponential = function(bb, obj) {
  return (obj || new ppx.Exponential).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Exponential.prototype.rate = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Exponential.startExponential = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rateOffset
 */
ppx.Exponential.addRate = function(builder, rateOffset) {
  builder.addFieldOffset(0, rateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Exponential.endExponential = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rateOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Exponential.createExponential = function(builder, rateOffset) {
  ppx.Exponential.startExponential(builder);
  ppx.Exponential.addRate(builder, rateOffset);
  return ppx.Exponential.endExponential(builder);
}

/**
 * @constructor
 */
ppx.Weibull = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ppx.Weibull}
 */
ppx.Weibull.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ppx.Weibull=} obj
 * @returns {ppx.Weibull}
 */
ppx.Weibull.getRootAsWeibull = function(bb, obj) {
  return (obj || new ppx.Weibull).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Weibull.prototype.scale = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {ppx.Tensor=} obj
 * @returns {ppx.Tensor|null}
 */
ppx.Weibull.prototype.concetration = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new ppx.Tensor).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ppx.Weibull.startWeibull = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} scaleOffset
 */
ppx.Weibull.addScale = function(builder, scaleOffset) {
  builder.addFieldOffset(0, scaleOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} concetrationOffset
 */
ppx.Weibull.addConcetration = function(builder, concetrationOffset) {
  builder.addFieldOffset(1, concetrationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ppx.Weibull.endWeibull = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} scaleOffset
 * @param {flatbuffers.Offset} concetrationOffset
 * @returns {flatbuffers.Offset}
 */
ppx.Weibull.createWeibull = function(builder, scaleOffset, concetrationOffset) {
  ppx.Weibull.startWeibull(builder);
  ppx.Weibull.addScale(builder, scaleOffset);
  ppx.Weibull.addConcetration(builder, concetrationOffset);
  return ppx.Weibull.endWeibull(builder);
}

// Exports for Node.js and RequireJS
this.ppx = ppx;
