// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

type Distribution = byte
const (
	DistributionNONE Distribution = 0
	DistributionNormal Distribution = 1
	DistributionUniform Distribution = 2
	DistributionCategorical Distribution = 3
	DistributionPoisson Distribution = 4
	DistributionGamma Distribution = 5
	DistributionLogNormal Distribution = 6
	DistributionExponential Distribution = 7
	DistributionWeibull Distribution = 8
)

var EnumNamesDistribution = map[Distribution]string{
	DistributionNONE:"NONE",
	DistributionNormal:"Normal",
	DistributionUniform:"Uniform",
	DistributionCategorical:"Categorical",
	DistributionPoisson:"Poisson",
	DistributionGamma:"Gamma",
	DistributionLogNormal:"LogNormal",
	DistributionExponential:"Exponential",
	DistributionWeibull:"Weibull",
}

