-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local Distribution = {
    NONE = 0,
    Normal = 1,
    Uniform = 2,
    Categorical = 3,
    Poisson = 4,
    Beta = 5,
    Gamma = 6,
    LogNormal = 7,
    Exponential = 8,
    Weibull = 9,
}

return Distribution -- return the module