<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

class Distribution
{
    const NONE = 0;
    const Normal = 1;
    const Uniform = 2;
    const Categorical = 3;
    const Poisson = 4;
    const Gamma = 5;
    const LogNormal = 6;
    const Exponential = 7;
    const Weibull = 8;

    private static $names = array(
        "NONE",
        "Normal",
        "Uniform",
        "Categorical",
        "Poisson",
        "Gamma",
        "LogNormal",
        "Exponential",
        "Weibull",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
