<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class LogNormal extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return LogNormal
     */
    public static function getRootAsLogNormal(ByteBuffer $bb)
    {
        $obj = new LogNormal();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function LogNormalIdentifier()
    {
        return "PPXF";
    }

    public static function LogNormalBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::LogNormalIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return LogNormal
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getMean()
    {
        $obj = new Tensor();
        $o = $this->__offset(4);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    public function getStddev()
    {
        $obj = new Tensor();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startLogNormal(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return LogNormal
     */
    public static function createLogNormal(FlatBufferBuilder $builder, $mean, $stddev)
    {
        $builder->startObject(2);
        self::addMean($builder, $mean);
        self::addStddev($builder, $stddev);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addMean(FlatBufferBuilder $builder, $mean)
    {
        $builder->addOffsetX(0, $mean, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addStddev(FlatBufferBuilder $builder, $stddev)
    {
        $builder->addOffsetX(1, $stddev, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endLogNormal(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
