// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct Gamma : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Gamma GetRootAsGamma(ByteBuffer _bb) { return GetRootAsGamma(_bb, new Gamma()); }
  public static Gamma GetRootAsGamma(ByteBuffer _bb, Gamma obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Gamma __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor? Concentration { get { int o = __p.__offset(4); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Tensor? Rate { get { int o = __p.__offset(6); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Gamma> CreateGamma(FlatBufferBuilder builder,
      Offset<Tensor> concentrationOffset = default(Offset<Tensor>),
      Offset<Tensor> rateOffset = default(Offset<Tensor>)) {
    builder.StartObject(2);
    Gamma.AddRate(builder, rateOffset);
    Gamma.AddConcentration(builder, concentrationOffset);
    return Gamma.EndGamma(builder);
  }

  public static void StartGamma(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddConcentration(FlatBufferBuilder builder, Offset<Tensor> concentrationOffset) { builder.AddOffset(0, concentrationOffset.Value, 0); }
  public static void AddRate(FlatBufferBuilder builder, Offset<Tensor> rateOffset) { builder.AddOffset(1, rateOffset.Value, 0); }
  public static Offset<Gamma> EndGamma(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Gamma>(o);
  }
};


}
