// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Exponential extends Table {
  public static Exponential getRootAsExponential(ByteBuffer _bb) { return getRootAsExponential(_bb, new Exponential()); }
  public static Exponential getRootAsExponential(ByteBuffer _bb, Exponential obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Exponential __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor rate() { return rate(new Tensor()); }
  public Tensor rate(Tensor obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createExponential(FlatBufferBuilder builder,
      int rateOffset) {
    builder.startObject(1);
    Exponential.addRate(builder, rateOffset);
    return Exponential.endExponential(builder);
  }

  public static void startExponential(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRate(FlatBufferBuilder builder, int rateOffset) { builder.addOffset(0, rateOffset, 0); }
  public static int endExponential(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

