// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Gamma extends Table {
  public static Gamma getRootAsGamma(ByteBuffer _bb) { return getRootAsGamma(_bb, new Gamma()); }
  public static Gamma getRootAsGamma(ByteBuffer _bb, Gamma obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Gamma __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor concentration() { return concentration(new Tensor()); }
  public Tensor concentration(Tensor obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public Tensor rate() { return rate(new Tensor()); }
  public Tensor rate(Tensor obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createGamma(FlatBufferBuilder builder,
      int concentrationOffset,
      int rateOffset) {
    builder.startObject(2);
    Gamma.addRate(builder, rateOffset);
    Gamma.addConcentration(builder, concentrationOffset);
    return Gamma.endGamma(builder);
  }

  public static void startGamma(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addConcentration(FlatBufferBuilder builder, int concentrationOffset) { builder.addOffset(0, concentrationOffset, 0); }
  public static void addRate(FlatBufferBuilder builder, int rateOffset) { builder.addOffset(1, rateOffset, 0); }
  public static int endGamma(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

