# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class Beta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBeta(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Beta()
        x.Init(buf, n + offset)
        return x

    # Beta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Beta
    def Low(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Beta
    def High(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BetaStart(builder): builder.StartObject(2)
def BetaAddLow(builder, low): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(low), 0)
def BetaAddHigh(builder, high): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(high), 0)
def BetaEnd(builder): return builder.EndObject()
